### PR TITLE
Add compatibility updates for use with OMP 3.3

### PR DESCRIPTION
**Pull request by ewhanson**
Hi @ajnyga,

This PR removes a deprecated DAO call and updates the templates to use the `{block}` formatting to add compatibility with OMP 3.3.

Let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by ajnyga** [comment]
Thanks, I appreciate the pr. The OMP quicksubmit I made is of course in no way official code. I will check these changes.

**Comment by ewhanson** [comment]
Hey @ajnyga, have you had a chance to look at this yet? If there's anything else missing, I'm happy to add it. Thanks!

**Comment by ajnyga** [comment]
Thanks, merged. Sorry for the delay, this was just lost among all other threads here.

**Comment by ewhanson** [comment]
No problem, thanks again!

**Pull request merged**
